import * as code from "vscode";
import * as fs from "fs/promises";
import * as path from "path";

interface WorkspaceFolder{
    path: string;
    name: string;
}

interface WorkspaceConfiguration{
    folders: WorkspaceFolder[];
    settings: {[key: string]: any};
}

export class PythonEnvironment {
    public excludedDirs: string[];
    public workspaceRoot: string;
    public pythonFilesPaths: Promise<string[]>;

    constructor(workspaceRoot: string, excludedDirs: string[]) {
        this.workspaceRoot = workspaceRoot.replace(/\\/g, '/');
        this.excludedDirs = excludedDirs;
        this.pythonFilesPaths = this.getFilePaths();
    }

    public createDotEnvFile(filePaths:string[]):void{
       let envFileName = path.join(this.workspaceRoot, '.env');
       let envFileContent:string[] = [];
       envFileContent.push('# This file is auto-generated by the Test Automation Python Environment extension.\nPYTHONPATH="');
       for(const filePath of filePaths){
            let fixedPath = filePath.replace(/\\/g, '/');
            envFileContent.push(`${fixedPath};`);
       }
       envFileContent.push('"');
       fs.writeFile(envFileName, envFileContent.join(''), { flag: 'w', encoding: 'utf-8' }); 
    }

    public async createPyEnvFile(filePath: string): Promise<void> {
        const pythonFileName = 'pyenv.py';
        const pythonDir = path.join(path.dirname(filePath), 'Lib');
        const fileRootPath = path.join(pythonDir, pythonFileName);
        try {
            const existingFile = await fs.stat(fileRootPath);
            if (existingFile.isFile()) {
                console.log(`File already exists: ${fileRootPath}`);
                return;
            }
        } catch (error: any) {
            if (error?.code !== 'ENOENT') {
                throw error;
            }
        }
        try {
            const dirStat = await fs.stat(pythonDir);
            if (!dirStat.isDirectory()) {
                throw new Error(`Path is not a directory: ${pythonDir}`);
            }
        } catch (error: any) {
            if (error?.code === 'ENOENT') {
                await fs.mkdir(pythonDir, { recursive: true });
            } else {
                throw error;
            }
        }
        await fs.writeFile(fileRootPath, PYENV_SCRIPT, { flag: 'w', encoding: 'utf-8' });
        console.log(`pyenv file created at: ${fileRootPath}`);
    }

    public async createCodeWorkspaceFile(): Promise<void> {
        const workspaceFileName = path.basename(this.workspaceRoot)
        const workspaceFilePath = `${this.workspaceRoot}/${workspaceFileName}.code-workspace`;
        const workspaceConfig: WorkspaceConfiguration = {
            folders:[{"name": `🚗 ${workspaceFileName}`, "path": "."}],
            settings: {
                "python.defaultInterpreterPath": "C:/LegacyApp/Python39/python.exe",
                "python.analysis.autoImportCompletions": true,
                "python.analysis.diagnosticSeverityOverrides": {
                    "reportArgumentType": "none",
                    "reportAttributeAccessIssue": "information",
                    "reportWildcardImportFromLibrary": "error",
                    "reportOptionalMemberAccess": "information"
                },
                "python.analysis.typeCheckingMode": "basic",
                "editor.formatOnSave": true,
                "editor.defaultFormatter": "ms-python.python",
                "python.analysis.fixAll": ["source.unusedImports"],
                "files.exclude": {
                    "**/.git": true,
                    "**/.venv": true,
                    "**/__pycache__": true,
                    "**/*.pyc": true,
                    "**/.pytest_cache": true,
                    "**/.mypy_cache": true
                },
                "search.exclude": {
                    "**/.venv": true,
                    "**/__pycache__": true,
                    "**/.pytest_cache": true
                },
                "python.terminal.launchArgs": [ "-m", "pyenv"],
                "launch": {
                    "version": "0.2.0",
                    "configurations": [
                        {
                            "name": "Python: Current File",
                            "type": "debugpy",
                            "request": "launch",
                            "program": "${file}",
                            "console": "integratedTerminal",
                            "justMyCode": true
                        }
                    ]
                }
            }
        }
        try{
            await fs.writeFile(workspaceFilePath, JSON.stringify(workspaceConfig, null, 4), { flag: 'w', encoding: 'utf-8' });
            const workspaceUri = code.Uri.file(workspaceFilePath);
            code.commands.executeCommand('vscode.openFolder', workspaceUri, {forceNewWindow: false});
        }catch (error:any){
            code.window.showErrorMessage(`Error creating workspace file: ${error.message}`);
        }
    }

    private async getFilePaths(): Promise<string[]> {
        // Search for Python files (.py)
        const files = await code.workspace.findFiles('**/*.py', '**/{' + this.excludedDirs.join(',') + '}/**');
        // Remove the .py file name from the path. only getting the unique paths of the files.
        const uniquePaths = new Set<string>();
        for(const file of files){
            uniquePaths.add(path.dirname(file.fsPath));
        }
        return Array.from(uniquePaths);
    }

    public async getCurrentPythonInterpreter(): Promise<string> {
        const python_ext = code.extensions.getExtension('ms-python.python'); // Python extension dependency.
        if(!python_ext) {
            code.window.showErrorMessage('Python extension not found.');
            return '';
        }
        // Wait for the extension to activate
        if(!python_ext.isActive) {
            await python_ext.activate();
        }
        const pythonApi = python_ext.exports;
        const interpreterDetails = await pythonApi.environments.getActiveEnvironmentPath();
        if(!interpreterDetails) {
            code.window.showErrorMessage('No Python interpreter found.');
            return '';
        }
        if(!interpreterDetails.path) {
            code.window.showErrorMessage('No Python interpreter path found.');
            return '';
        }
        return interpreterDetails?.path;
    }

}

const PYENV_SCRIPT = `# -*- coding: UTF-8 -*-
# ************************************************************************************************************
# License:    MIT                                                                                             
#                                                                                                             
# Permission is hereby granted, free of charge, to any person obtaining a copy                                
# of this software and associated documentation files (the "Software"), to deal                               
# in the Software without restriction, including without limitation the rights                                
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell                                   
# copies of the Software, and to permit persons to whom the Software is                                       
# furnished to do so, subject to the following conditions:                                                    
#                                                                                                             
# The above copyright notice and this permission notice shall be included in all                              
# copies or substantial portions of the Software.                                                             
#                                                                                                             
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR                                  
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,                                    
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE                                 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER                                      
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,                               
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE                               
# SOFTWARE.                                                                                                   
# Copyright (c) 2023 Juan Jose Solorzano.                                                                     
# ************************************************************************************************************
# Python:     >3.9                                                                                            
# Depencies:  os, sys, fnmatch, runpy                                                                         
# Author:     $Author:    Solorzano, Juan Jose                                                                
# Date:       $Date:      20/06/26                                                                            
# ************************************************************************************************************
# Module information:                                                                                         
# ------------------------------------------------------------------------------------------------------------
# This module provides utilities for managing Python environment paths and executing scripts.                 
#                                                                                                             
# Functions:                                                                                                  
# - getAllPaths(targetPath): Retrieves all paths containing Python files starting from the target path.       
# - getSuiteRootPath(start_dir): Identifies the root path of the suite by searching for a .code-workspace     
#   file.                                                                                                      
# - setSysPath(pathList): Adds specified paths to the Python sys.path for module resolution.                  
#                                                                                                             
# Usage:                                                                                                      
# Run this script with a target Python script as an argument to execute it within the configured environment. 
# Example: python pyenv.py <target_script>                                                                    
# ************************************************************************************************************

import sys
import os
import fnmatch #type: ignore
import runpy #type: ignore

def getAllPaths(targetPath):
    """
    Returns all paths starting from the mainPath as a list of strings
    Returns [] if mainPath was not found
    Returns [mainPath] if mainPath has no sub-paths
    """
    pathList = []
    for path, _, files in os.walk(targetPath): 
        # add only folders that contains a .py source file
        for fileName in files:
            if fnmatch.fnmatch(fileName, "*.py"):
                if path.__contains__("__pycache__"):
                    continue
                pathList.append(path)
                break
    return pathList

def getSuiteRootPath(start_dir=os.getcwd()):
    """
    Returns the root path of the suite
    """
    current_dir = start_dir
    levels = 50  # Number of levels to go up
    root_path = None
    for _ in range(levels):
        #current_dir = os.path.dirname(current_dir) #BUG: This line fails during testing, it was commented out.
        for file in os.listdir(current_dir):
            if fnmatch.fnmatch(file, "*.code-workspace"):
                root_path = current_dir
                break
    return root_path 

def setSysPath(pathList):
    """
    Adds the paths in pathList to sys.path
    """
    for path in pathList:
        if path not in sys.path:
            sys.path.append(path)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python pyenv.py <target_script>")
        sys.exit(1)
    target = sys.argv[1]
    if not os.path.isfile(target):
        print("Error: The file %s does not exist."%target)
        sys.exit(1)
    suite_root_path = getSuiteRootPath()
    all_paths = getAllPaths(suite_root_path)
    setSysPath(all_paths)
    # Execute the external script using runpy for better safety and efficiency
    try:
        runpy.run_path(target, run_name="__main__")
    except Exception as e:
        print(f"Error while executing the script: \\n\\t{e}")`;